metadata:
  labels:
    app.kubernetes.io/version: "${GRAFANA_VERSION}"
spec:
  template:
    spec:
      containers:
      - name: grafana
        image: s2.ubuntu.home:5000/docker.io/grafana/grafana:${GRAFANA_VERSION}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: config
            mountPath: /etc/grafana/grafana.ini
            subPath: grafana.ini
          - name: storage
            mountPath: /var/lib/grafana
          - name: sc-dashboard-volume
            mountPath: /tmp/dashboards
          - name: sc-dashboard-provider
            mountPath: /etc/grafana/provisioning/dashboards/sc-dashboardproviders.yaml
            subPath: provider.yaml
          - name: sc-datasources-volume
            mountPath: /etc/grafana/provisioning/datasources