apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-web
  namespace: web
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1M
  volumeName: nas-web