kind: Service
apiVersion: v1
metadata:
  name: web
  namespace: web
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: web
spec:
  externalTrafficPolicy: Cluster 
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web 
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
