apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cmak-ingress
  namespace: cmak
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  defaultBackend:
    service:
      name: cmak
      port:
        number: 80
  rules:
  - host: "cmak.k8s.home"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cmak
              port:
                number: 80
