apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-web
spec:
  capacity:
    storage: 1M
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nas.home
    path: "/volume1/K8S"
    readOnly: true
  mountOptions:
    - nfsvers=4
