apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: web
  labels:
    app.kubernetes.io/component: ingress
    app.kubernetes.io/name: nginx-ingress-microk8s
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    prometheus.io/port: "9113"
    spec.ingressClassName: public
spec:
  rules:
  - host: web.prod.k8s.home
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: web
              port:
                number: 80
