apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-targets
  namespace: monitoring
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.26.0
    prometheus: k8s
data:
  http-targets.json: |-
    [{"targets":["ballantyne.home:9182"],
      "labels":{"job":"node-exporter","origin":"windows-nodes"}},
     {"targets":["nas.home:9100","wdmycloud.home:9100","pi.ubuntu.home:9100","s2.ubuntu.home:9100","s3.ubuntu.home:9100","s4.ubuntu.home:9100"],
      "labels":{"job":"node-exporter","origin":"unix-nodes"}},
     {"targets":["s3.ubuntu.home:9999","s4.ubuntu.home:9999","s8.ubuntu.home:9999"],
      "labels":{"job":"kafka-nodes"}}]
  tcp-targets.json: |-
    [{"targets":["s3.ubuntu.home:7200","s4.ubuntu.home:7200","s8.ubuntu.home:7200"],
      "labels":{"job":"zookeepers"}},
     {"targets":["s3.ubuntu.home:7201","s4.ubuntu.home:7201","s8.ubuntu.home:7201"],
      "labels":{"job":"brokers"}}]
