apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: external-nodes
  namespace: monitoring
spec:
  jobName: node-exporter 
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
    scheme: http
    path: /probe
  tlsConfig:
    insecureSkipVerify: true
  targets:
    staticConfig:
      static:
        - s3.ubuntu.home:9100/metrics
        - s4.ubuntu.home:9100/metrics
      relabelingConfigs:
        - sourceLabels: [__param_target]
          separator: ':'
          replacement: $1
          targetLabel: instance
          action: replace
