apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: external
  namespace: monitoring
spec:
  jobName: exporter 
  interval: 10s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
    scheme: http
  targets:
    staticConfig:
      static:
        - s3.ubuntu.home
        - s4.ubuntu.home
