apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hp-devpi
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /tmp/pv-devpi