apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hp-devpi
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: devpi
    name: pvc-devpi
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /tmp/pv-devpi