apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-devpi
  namespace: devpi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: microk8s-hostpath
  volumeName: pv-hp-devpi
