apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-devpi
  namespace: devpi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
  volumeName: pv-hp-devpi