apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devpi-ingress
  namespace: devpi
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Access-Control-Allow-Origin https://web.prod.k8s.home always;
spec:
  ingressClassName: public
  rules:
  - host: devpi.prod.k8s.home
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: devpi
              port:
                number: 3141
