metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
    prometheus.io/scheme: http    
spec:
  template:
    spec:
      image: "k8s.gcr.io/ingress-nginx/controller:v1.1.0"
