apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-recipes
  namespace: recipes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1M
  selector:
    matchLabels:
      pv-key: k8s-smb
  storageClassName: smb-storage
