apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-oregon
  namespace: oregon
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1M
  selector:
    matchLabels:
      pv-key: k8s-smb
  storageClassName: smb-storage
