apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oregon-ingress
  namespace: oregon
  annotations:
    spec.ingressClassName: public
#    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  defaultBackend:
    service:
      name: oregon
      port:
        number: 443
  rules:
  - host: "oregon.k8s.home"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: oregon
              port:
                number: 80
