apiVersion: v1
kind: PersistentVolume
metadata:
  name: s7-local-hd
spec:
  capacity:
    storage: 850000000000
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hd-storage
  local:
    path: /mnt/k8s
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - s7.ubuntu.home
