apiVersion: v1
kind: ConfigMap
metadata:
  name: web-metrics
  namespace: stormshot
  labels:
    k8s-app: web 
data:
  metrics.conf: |
    server {
        listen       8080;
        server_name  metrics;
    
        location /metrics {
            stub_status;
    
            access_log off;
            allow 127.0.0.1;
            deny all;
        }
    
        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
