apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-stormshot
  namespace: stormshot
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 30M
  volumeName: nas-stormshot
