apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-recipes
  namespace: recipes
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 30M
  volumeName: nas-recipes
