apiVersion: v1
kind: Service
metadata:
  name: recipes
  namespace: recipes
  labels:
    app.kubernetes.io/component: recipes
    app.kubernetes.io/name: recipes
spec:
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: recipes 
  selector:
    app.kubernetes.io/component: recipes
    app.kubernetes.io/name: recipes
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
