apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hp-postgres
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /tmp/pv-postgres
