apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: pgadmin4
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LnVidW50dS5ob21lIjp7InVzZXJuYW1lIjoiYm9iYiIsInBhc3N3b3JkIjoiMTIzT2xlYXJ5IiwiZW1haWwiOiJib2JiQGs4cy5ob21lIiwiYXV0aCI6IlltOWlZam94TWpOUGJHVmhjbms9In19fQ==
type: kubernetes.io/dockerconfigjson

