apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin4-pv-claim
  namespace: pgadmin4
  labels:
    type: local
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100M
  selector:
    matchLabels:
      pv-key: k8s-smb
  storageClassName: smb-storage
