apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hp-pgadmin4
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: pgadmin4
    name: pvc-pgadmin4
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /tmp/pv-pgadmin4