apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pgadmin4
  namespace: pgadmin4
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
  volumeName: pv-hp-pgadmin4