kind: Deployment
apiVersion: apps/v1
metadata:
  name: pgadmin4
  namespace: pgadmin4
  labels:
    app.kubernetes.io/component: pgadmin4
    app.kubernetes.io/name: pgadmin4
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: pgadmin4
      app.kubernetes.io/name: pgadmin4
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pgadmin4
        app.kubernetes.io/name: pgadmin4
    spec:
      volumes:
        - name: pgadmin4-storage
          persistentVolumeClaim:
            claimName: pvc-pgadmin4
      containers:
        - name: pgadmin4
          image:  s2.ubuntu.home:5000/docker.io/dpage/pgadmin4:8.12
          envFrom:
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin4
                  key: username
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin4
                  key: password
            - name: PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT
              value: 'False'
            - name: PGADMIN_CONFIG_WTF_CSRF_ENABLED
              value: 'False'
#            - name: CONFIG_DATABASE_URI
#              valueFrom:
#                secretKeyRef:
#                  name: pgadmin4
#                  key: config_db
          ports:
            - name: pgadmin4
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: pgadmin4-storage
              mountPath: /var/lib/pgadmin
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: pgadmin4
      serviceAccount: pgadmin4
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
