kind: Service
apiVersion: v1
metadata:
  name: pgadmin4
  namespace: pgadmin4
  labels:
    app.kubernetes.io/component: pgadmin4
    app.kubernetes.io/name: pgadmin4
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: pgadmin4
  selector:
    app.kubernetes.io/component: pgadmin4
    app.kubernetes.io/name: pgadmin4
  sessionAffinity: None
  type: LoadBalancer
