kind: Service
apiVersion: v1
metadata:
  name: jenkins-exporter
  namespace: jenkins-exporter
  labels:
    app.kubernetes.io/component: jenkins-exporter
    app.kubernetes.io/name: jenkins-exporter
    prometheus.monitoring/service: jenkins-exporter 
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9118
      targetPort: metrics
  selector:
    app.kubernetes.io/component: jenkins-exporter
    app.kubernetes.io/name: jenkins-exporter
    prometheus.monitoring/service: jenkins-exporter 
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
