apiVersion: v1
kind: PersistentVolume
metadata:
  name: hp-postgres
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: postgres
    name: pvc-postgres
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
