apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: postgres
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100M
  selector:
    matchLabels:
      pv-key: k8s-smb
  storageClassName: smb-storage
