apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  volumeName: pv-smb-postgres
#  selector:
#    matchLabels:
#      pv-key: k8s-smb
  storageClassName: smb-storage
