apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/component: external-nodes
    app.kubernetes.io/name: external-nodes
  name: windows-nodes
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.3.1.3
    nodeName: ballantyne.home
  ports:
  - name: http
    port: 9182
    protocol: TCP
