apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/component: external-nodes
    app.kubernetes.io/name: windows-nodes
  name: windows-nodes
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.3.1.3
    nodeName: ballantyne.home
#    targetRef:
#      kind: Endpoint
#      namespace: monitoring
  - name: http
    port: 9182
    protocol: TCP
