apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: jmx-node-exporter
  name: jmx-nodes
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  endpoints:
    - interval: 60s
      targetPort: 7200
      scheme: tcp
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
          regex: (.*)
          action: replace
          replacement: $1
    - interval: 60s
      targetPort: 7201
      scheme: tcp
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
          regex: (.*)
          action: replace
          replacement: $1
  jobLabel: app.kubernetes.io/name
  selector:
      matchLabels:
        app.kubernetes.io/name: jmx-nodes
        app.kubernetes.io/component: external-nodes
