spec:
  template:
    spec:
      containers:
        - name: nginx-ingress-microk8s
          image: registry.k8s.io/ingress-nginx/controller:v1.11.2
          args:
            - /nginx-ingress-controller
            - '--configmap=$(POD_NAMESPACE)/nginx-load-balancer-microk8s-conf'
            - '--tcp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-tcp-microk8s-conf'
            - '--udp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-udp-microk8s-conf'
            - '--default-ssl-certificate=$(POD_NAMESPACE)/sohoball-ca'
            - '--ingress-class=public'
            - ' '
            - '--publish-status-address=127.0.0.1'
