- job_name: "http-configs"
  scrape_interval: 60s
  scheme: http
  metrics_path: "/metrics"
  file_sd_configs:
    - files:
        - "/etc/prometheus/configmaps/additional-targets/http-targets.json"
  relabel_configs:
    - action: replace
      source_labels: [__address__]
      target_label: instance
      regex: '([^:]+)(:[0-9]+)?'
      replacement: '${1}' 
- job_name: 'zookeeper-exporter'
  dns_sd_configs:
    - names:
        - 's3.ubuntu.home'
        - 's4.ubuntu.home'
        - 's8.ubuntu.home'
      type: 'A'
      port: 7202
  relabel_configs:
    - action: replace
      source_labels: [__address__]
      target_label: hostname
      regex: '([^:]+)(:[0-9]+)?'
      replacement: '${1}' 
    - action: replace
      source_labels: [__meta_dns_name]
      target_label: instance
- job_name: 'kafka-exporter'
  dns_sd_configs:
    - names:
        - 's3.ubuntu.home'
        - 's4.ubuntu.home'
        - 's8.ubuntu.home'
      type: 'A'
      port: 7204
  relabel_configs:
    - action: replace
      source_labels: [__address__]
      target_label: hostname
      regex: '([^:]+)(:[0-9]+)?'
      replacement: '${1}' 
    - action: replace
      source_labels: [__meta_dns_name]
      target_label: instance
